{
 "title": "PostgreSQL Query Drill-Down",
 "tags": [ "postgres" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(pg_up,instance)" } },
   {
    "name": "queryid",
    "label": "Query ID",
    "query": {
     "query": "label_values(pg_stat_statements_calls{instance=\"$instance\",datname!~\"template.*\"},queryid)"
    }
   },
   {
    "name": "query",
    "label": "Query",
    "query": {
     "query": "label_values(pg_stat_statements_calls{queryid=\"$queryid\"},query)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Query $queryid",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<font color=#5991A7><b><center>$query</center></b></font>"
   }
  },
  {
   "title": "Query Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_calls{instance=\"$instance\",queryid=~\"$queryid\"}[$interval]) or \nirate(pg_stat_statements_calls{instance=\"$instance\",queryid=~\"$queryid\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Query Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_total_time_seconds{instance=~\"$instance\",queryid=~\"$queryid\"}[$interval]) or\nirate(pg_stat_statements_total_time_seconds{instance=~\"$instance\",queryid=~\"$queryid\"}[5m])) by (datname, queryid)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Query Time per Call",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_total_time_seconds{instance=~\"$instance\",queryid=~\"$queryid\"}[$interval]) / \n(rate(pg_stat_statements_calls{instance=~\"$instance\",queryid=~\"$queryid\"}[$interval]) > 0)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Retrieved or Affected  Rows",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_rows{instance=~\"$instance\",queryid=~\"$queryid\"}[$interval])) by (queryid, datname)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rows Processed per Call",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_rows{instance=~\"$instance\",queryid=~\"$queryid\"}[$interval]) / \nrate(pg_stat_statements_calls{instance=~\"$instance\",queryid=~\"$queryid\"}[$interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{queryid}} - {{datname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}